### PR TITLE
fix(llamaindex): pass valid EpisodeType enum instead of invalid "text" string

### PR DESCRIPTION
**Pull request by connectsudhindra-gif**
## Summary
- `MemMachineMemory.add()` in `integrations/llamaindex/mem_machine_memory.py` called `memory.add(episode_type="text", ...)`, passing a raw string where `Memory.add()` expects an `EpisodeType` enum.
- `Memory._build_memory_message()` calls `episode_type.value` internally, so this raised `AttributeError: 'str' object has no attribute 'value'` on every call to `add()`/`put()`.
- `"text"` was also never a valid `EpisodeType` value in the first place (the enum only defines `MESSAGE = "message"`), so simply string-normalizing it (as was done for the LangGraph integration in #1403) wouldn't have been enough here.
- Fix: pass `EpisodeType.MESSAGE` directly, matching the only valid episode type today.
- This is the same failure mode reported in #1002 for the LangGraph integration, which was already fixed by #1403 but never linked back to that issue.

## Test plan
- Added `integrations/llamaindex/test_mem_machine_memory.py` with two unit tests (mocking the backend `Memory`) that assert `episode_type` is forwarded as a real `EpisodeType.MESSAGE` enum via both `add()` and `put()`.
- Verified the new tests fail against the pre-fix code with the exact same shape of error class this bug produces, and pass after the fix.
- Ran `ruff check` and `ruff format --diff` on both changed files: clean.

### CODE REVIEW

**Comment by connectsudhindra-gif** [comment]
This is ready for review whenever a maintainer has time. Let me know if any changes are needed.

**Comment by connectsudhindra-gif** [comment]
@ChristianKniep / @jgong  / @jealous pls review
