### ISSUE TITLE
[Bug]: Test python client package imports with python 3.10 always fail

### ISSUE THREAD

**Issue by jgong** [MemMachine/MemMachine#1050]
### Describe the bug

Test python client package with python 3.10 always fail https://github.com/MemMachine/MemMachine/actions/runs/21654191709/job/62425447069?pr=1036

### Steps to reproduce

Check the error logs reported in action run: https://github.com/MemMachine/MemMachine/actions/runs/21654191709/job/62425447069?pr=1036#logs
```
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/opt/hostedtoolcache/Python/3.10.19/x64/lib/python3.10/site-packages/memmachine/__init__.py", line 4, in <module>
    from memmachine.rest_client import MemMachineClient, Memory, Project
  File "/opt/hostedtoolcache/Python/3.10.19/x64/lib/python3.10/site-packages/memmachine/rest_client/__init__.py", line 9, in <module>
    from .config import Config
  File "/opt/hostedtoolcache/Python/3.10.19/x64/lib/python3.10/site-packages/memmachine/rest_client/config.py", line 10, in <module>
    from memmachine.common.api.config_spec import (
  File "/opt/hostedtoolcache/Python/3.10.19/x64/lib/python3.10/site-packages/memmachine/common/api/config_spec.py", line 3, in <module>
    from enum import StrEnum
ImportError: cannot import name 'StrEnum' from 'enum' (/opt/hostedtoolcache/Python/3.10.19/x64/lib/python3.10/enum.py)
Error: Process completed with exit code 1.
```

`StrEnum` class was officially introduced into the Python standard library in Python 3.11.

### Expected behavior

python client package imports should work with Python 3.10

### Environment

- Python 3.10

**Comment by sscargal** [comment]
This should be fixed by PR #1052, which introduces independent Server and Client packages with independent `ruff` tests.
