### PR TITLE
Improve `tools/chatgpt2memmachine` migration tool to allow resume from previous run

### LINKED ISSUE #1001: [Feat] Improve chat import: required workers, resume support, timing metrics
### Status:
I imported my ChatGPT history (2304 conversations / 21,589 messages). With default --workers=1 it took ~24 hours. If the process is killed, I have to start from scratch, which is very painful for large imports.

### Describe the solution you'd like

1) Make `--workers` flag required for migration/import to reduce runtime.
2) Add resume/continue support: skip already imported messages using unique `message_id` in metadata (message_id + chat_id).
3) Record and print total import duration at the end of the migration (overall elapsed time).

### Describe alternatives you've considered

_No response_

### Additional context

https://github.com/MemMachine/MemMachine/pull/997#event-22360877955

### PR DESCRIPTION
**Pull request by jgong**
### Purpose of the change

Improvements of migrating chats into MemMachine:
1. Check `--workers` flag and prompt to ask user to confirm the number of workers when large amount of messages
2. Write trace information into file when verbose mode
2. Add `run_id` in each migration execution, check response of adding memory request, record message ids into success_${run_id}.txt or errors_${run_id}.txt
3. allow user to resume from previous run with `--run-id` + `--resume`
4. allow user to retry failed messages from previous run with `--run-id` + `--retry-failed`

### Description

Please include a summary of the change and the issue it addresses. Please also include relevant motivation and context. List any dependencies that are required for this change.

### Fixes/Closes

Fixes #1001

### Type of change

[Please delete options that are not relevant.]

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (does not change functionality, e.g., code style improvements, linting)
- [ ] Documentation update
- [ ] Project Maintenance (updates to build scripts, CI, etc., that do not affect the main project)
- [ ] Security (improves security without changing functionality)

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

[Please delete options that are not relevant.]

- [ ] Unit Test
- [ ] Integration Test
- [x] End-to-end Test
- [ ] Test Script (please provide)
- [ ] Manual verification (list step-by-step instructions)

**Test Results:** [Attach logs, screenshots, or relevant output]

Resume from previous run
```
(memmachine) jinggong@Jings-MBP chatgpt2memmachine % python migration.py -i data/conversations-chatgpt.json -v -
-run-id 20260203T094422586793 --resume
Loaded 2 successful message records from previous run
DEBUG: Loading OpenAI input file data/conversations-chatgpt.json
Found 6 conversation(s)
Run ID: 20260203T094422586793
Resume mode: Loading all conversations, will skip messages from success file
Adding memories to MemMachine...
Filtered 1 message(s) based on previous run results
No messages to process after filtering (original: 1 messages)
Completed conversation 1 (0 messages)
Filtered 1 message(s) based on previous run results
Completed conversation 2 (2 messages)
Completed conversation 3 (2 messages)
Completed conversation 4 (1 messages)
Completed conversation 5 (4 messages)
Completed conversation 6 (1 messages)
Migration complete
Run ID: 20260203T094422586793
Statistics saved to: output/migration_stats_20260203T094422586793.json
```

Retry failed messages
```
(memmachine) jinggong@Jings-MBP chatgpt2memmachine % python migration.py -i data/conversations-chatgpt.json -v --run-id 20260203T094422586793 --retry-failed
Loaded 1 failed message records from previous run
DEBUG: Loading OpenAI input file data/conversations-chatgpt.json
Found 6 conversation(s)
Run ID: 20260203T094422586793
Optimized: Processing 1 conversation(s) with failed messages
Adding memories to MemMachine...
Completed conversation 1 (1 messages)
Migration complete
Run ID: 20260203T094422586793
Statistics saved to: output/migration_stats_20260203T094422586793.json
```

### Checklist

[Please delete options that are not relevant.]

- [x] I have signed the commit(s) within this pull request
- [x] My code follows the style guidelines of this project (See STYLE_GUIDE.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added unit tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### Maintainer Checklist

- [ ] Confirmed all checks passed
- [ ] Contributor has signed the commit(s)
- [ ] Reviewed the code
- [ ] Run, Tested, and Verified the change(s) work as expected

### Screenshots/Gifs

[If applicable, add screenshots or GIFs that show the changes in action. This is especially helpful for API responses. Otherwise, delete this section or type "N/A".]

### Further comments

[Add any other relevant information here, such as potential side effects, future considerations, or any specific questions for the reviewer. Otherwise, type "None".]

### CODE REVIEW

**Comment by jgong** [comment]
The failure is from test with python 3.10
```
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/opt/hostedtoolcache/Python/3.10.19/x64/lib/python3.10/site-packages/memmachine/__init__.py", line 4, in <module>
    from memmachine.rest_client import MemMachineClient, Memory, Project
  File "/opt/hostedtoolcache/Python/3.10.19/x64/lib/python3.10/site-packages/memmachine/rest_client/__init__.py", line 9, in <module>
    from .config import Config
  File "/opt/hostedtoolcache/Python/3.10.19/x64/lib/python3.10/site-packages/memmachine/rest_client/config.py", line 10, in <module>
    from memmachine.common.api.config_spec import (
  File "/opt/hostedtoolcache/Python/3.10.19/x64/lib/python3.10/site-packages/memmachine/common/api/config_spec.py", line 3, in <module>
    from enum import StrEnum
ImportError: cannot import name 'StrEnum' from 'enum' (/opt/hostedtoolcache/Python/3.10.19/x64/lib/python3.10/enum.py)
Error: Process completed with exit code 1.
```

`StrEnum` class was officially introduced into the Python standard library in Python 3.11. CC @edwinyyyu since it is introduced in https://github.com/MemMachine/MemMachine/pull/1043
